config/routes.rb
Rails.application.routes.draw do
  resources :checks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'pages#home'
  get '/index', to: 'pages#index'
  get '/users/:id', to: 'pages#index'
  root to: "pages#index"
  root 'pages#index'
  get '/setup', to:'pages#setup'

end

app/models/check.rb
class Check < ApplicationRecord
  extend FriendlyId
  friendly_id :hashkey, use: :slugged
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]

  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
    request.headers["Content-Type"] # => "application/json"
    result =Check.friendly.find(params[:id]).combination.to_s

    response.headers['HEADER NAME'] = result

    response.headers['Access-Control-Allow-Origin'] = '*'
  end

  # GET /checks/new
  def new
    response.headers['Access-Control-Allow-Origin'] = '*'
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit

    if params[:pin1].present?
      @updated_value1 = params[:pin1]
      check = Check.friendly.find(params[:id])
      check.pin1 = @updated_value1
      check.save
    end
    if params[:pin2].present?
      @updated_value2 = params[:pin2]
      check = Check.friendly.find(params[:id])
      check.pin2 = @updated_value2
      check.save
    end
    if params[:pin3].present?
      @updated_value3 = params[:pin3]
      check = Check.friendly.find(params[:id])
      check.pin3 = @updated_value3
      check.save
    end
    if params[:pin4].present?
      @updated_value4 = params[:pin4]
      check = Check.friendly.find(params[:id])
      check.pin4 = @updated_value4
      check.save
    end




  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    respond_to do |format|r
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url, notice: 'Check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:pin1, :pin2, :pin3, :pin4,:slug)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= simple_form_for(@check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pin1 %>
    <%= f.input :pin2 %>
    <%= f.input :pin3 %>
    <%= f.input :pin4 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing Check</h1>

<%= render 'form', check: @check %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checks</h1>

<table>
  <thead>
    <tr>
      <th>Pin1</th>
      <th>Pin2</th>
      <th>Pin3</th>
      <th>Pin4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= check.pin1 %></td>
        <td><%= check.pin2 %></td>
        <td><%= check.pin3 %></td>
        <td><%= check.pin4 %></td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if @checks.nil? %>
<%= link_to 'New Check', new_check_path %>
<%end%>

app/views/checks/new.html.erb
<h1>New Check</h1>

<%= render 'form', check: @check %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pin1:</strong>
  <%= @check.pin1 %>
</p>

<p>
  <strong>Pin2:</strong>
  <%= @check.pin2 %>
</p>

<p>
  <strong>Pin3:</strong>
  <%= @check.pin3 %>
</p>

<p>
  <strong>Pin4:</strong>
  <%= @check.pin4 %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>